drop table if exists board CASCADE;
CREATE TABLE board (
       board_id          bigint generated by default as identity,
       title             varchar(100),
       board_category    bigint,
       contents          text,
       member_id         bigint,
       upload_date       timestamp,
       edit_date         timestamp,
       delete_date       timestamp,
       views             int,
       primary key (board_id)
);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 1', 1, '이것은 테스트 데이터 입니다.', 1,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 2', 1, '이것은 테스트 데이터 입니다.', 2,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 3', 1, '이것은 테스트 데이터 입니다.', 1,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 4', 1, '이것은 테스트 데이터 입니다.', 2,now(), 0);
insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 5', 1, '이것은 테스트 데이터 입니다.', 3,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 6', 1, '이것은 테스트 데이터 입니다.', 2,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 7', 1, '이것은 테스트 데이터 입니다.', 1,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 8', 1, '이것은 테스트 데이터 입니다.', 2,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 9', 1, '이것은 테스트 데이터 입니다.', 1,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 10', 1, '이것은 테스트 데이터 입니다.', 2,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 11', 1, '이것은 테스트 데이터 입니다.', 1,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 12', 1, '이것은 테스트 데이터 입니다.', 2,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 13', 1, '이것은 테스트 데이터 입니다.', 1,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 14', 1, '이것은 테스트 데이터 입니다.', 2,now(), 0);