drop table if exists board CASCADE;
CREATE TABLE board (
       board_id          bigint generated by default as identity,
       title             varchar(100),
       board_category    bigint,
       contents          text,
       member_id         bigint,
       upload_date       timestamp,
       edit_date         timestamp,
       delete_date       timestamp,
       views             int,
       primary key (board_id)
);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 1', 1, '이것은 테스트 데이터 입니다.', 1,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 2', 1, '이것은 테스트 데이터 입니다.', 2,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 3', 1, '이것은 테스트 데이터 입니다.', 1,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 4', 1, '이것은 테스트 데이터 입니다.', 2,now(), 0);
insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 5', 1, '이것은 테스트 데이터 입니다.', 3,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 6', 1, '이것은 테스트 데이터 입니다.', 2,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 7', 1, '이것은 테스트 데이터 입니다.', 1,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 8', 1, '이것은 테스트 데이터 입니다.', 2,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 9', 1, '이것은 테스트 데이터 입니다.', 1,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 10', 1, '이것은 테스트 데이터 입니다.', 2,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 11', 1, '이것은 테스트 데이터 입니다.', 1,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 12', 1, '이것은 테스트 데이터 입니다.', 2,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 13', 1, '이것은 테스트 데이터 입니다.', 1,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 14', 1, '이것은 테스트 데이터 입니다.', 2,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 1', 1, '이것은 테스트 데이터 입니다.1', 1,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 2', 1, '이것은 테스트 데이터 입니다.2', 2,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 3', 1, '이것은 테스트 데이터 입니다.3', 1,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 4', 1, '이것은 테스트 데이터 입니다.4', 2,now(), 0);
insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 5', 1, '이것은 테스트 데이터 입니다.5', 3,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 6', 1, '이것은 테스트 데이터 입니다.6', 2,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 7', 1, '이것은 테스트 데이터 입니다.7', 1,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 8', 1, '이것은 테스트 데이터 입니다.8', 2,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 9', 1, '이것은 테스트 데이터 입니다.9', 1,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 10', 1, '이것은 테스트 데이터 입니다.10', 2,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 11', 1, '이것은 테스트 데이터 입니다.11', 1,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 12', 1, '이것은 테스트 데이터 입니다.12', 2,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 13', 1, '이것은 테스트 데이터 입니다.13', 1,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 14', 1, '이것은 테스트 데이터 입니다.14', 2,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 1', 2, '이것은 테스트 데이터 입니다.1', 1,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 2', 2, '이것은 테스트 데이터 입니다.2', 2,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 3', 2, '이것은 테스트 데이터 입니다.3', 1,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 4', 2, '이것은 테스트 데이터 입니다.4', 2,now(), 0);
insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 5', 2, '이것은 테스트 데이터 입니다.5', 3,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 6', 2, '이것은 테스트 데이터 입니다.6', 2,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 7', 2, '이것은 테스트 데이터 입니다.7', 1,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 8', 2, '이것은 테스트 데이터 입니다.8', 2,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 9', 2, '이것은 테스트 데이터 입니다.9', 1,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 10', 2, '이것은 테스트 데이터 입니다.10', 2,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 11', 2, '이것은 테스트 데이터 입니다.11', 1,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 12', 2, '이것은 테스트 데이터 입니다.12', 2,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 13', 2, '이것은 테스트 데이터 입니다.13', 1,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 14', 2, '이것은 테스트 데이터 입니다.14', 2,now(), 0);


insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 15', 2, '이것은 테스트 데이터 입니다.1', 1,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 16', 2, '이것은 테스트 데이터 입니다.2', 2,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 17', 2, '이것은 테스트 데이터 입니다.3', 1,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 18', 2, '이것은 테스트 데이터 입니다.4', 2,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 19', 2, '이것은 테스트 데이터 입니다.5', 3,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 20', 2, '이것은 테스트 데이터 입니다.6', 2,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 21', 2, '이것은 테스트 데이터 입니다.7', 1,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 22', 2, '이것은 테스트 데이터 입니다.8', 2,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 23', 2, '이것은 테스트 데이터 입니다.9', 1,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 24', 2, '이것은 테스트 데이터 입니다.10', 2,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 25', 2, '이것은 테스트 데이터 입니다.11', 1,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 26', 2, '이것은 테스트 데이터 입니다.12', 2,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 27', 2, '이것은 테스트 데이터 입니다.13', 1,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 28', 2, '이것은 테스트 데이터 입니다.14', 2,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 29', 2, '이것은 테스트 데이터 입니다.5', 3,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 30', 2, '이것은 테스트 데이터 입니다.6', 2,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 31', 2, '이것은 테스트 데이터 입니다.7', 1,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 32', 2, '이것은 테스트 데이터 입니다.8', 2,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 33', 2, '이것은 테스트 데이터 입니다.9', 1,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 34', 2, '이것은 테스트 데이터 입니다.10', 2,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 35', 2, '이것은 테스트 데이터 입니다.11', 1,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 36', 2, '이것은 테스트 데이터 입니다.12', 2,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 37', 2, '이것은 테스트 데이터 입니다.13', 1,now(), 0);

insert into board
(title, board_category, contents, member_id, upload_date, views)
VALUES ('테스트 제목 38', 2, '이것은 테스트 데이터 입니다.14', 2,now(), 0);