drop table if exists comment CASCADE;
CREATE TABLE comment (
                       comment_id       bigint generated by default as identity,
                       board_id         bigint,
                       member_id        bigint,
                       head_comment     bigint,
                       contents         varchar(1000),
                       upload_date      timestamp,
                       edit_date        timestamp,
                       delete_date      timestamp,

                       primary key (comment_id)
);

insert into comment
(board_id, member_id, head_comment, contents, upload_date)
VALUES (1, 1, 0,'동일인물 테스트 댓글 1', now());

insert into comment
(board_id, member_id, head_comment, contents, upload_date)
VALUES (1, 1, 0,'동일인물 테스트 댓글 2', now());

insert into comment
(board_id, member_id, head_comment, contents, upload_date)
VALUES (1, 2, 0,'테스트 댓글 3', now());

insert into comment
(board_id, member_id, head_comment, contents, upload_date)
VALUES (1, 2, 1,'테스트 대댓글 1', now());

insert into comment
(board_id, member_id, head_comment, contents, upload_date)
VALUES (1, 1, 1,'본인 테스트 대댓글 1', now());

insert into comment
(board_id, member_id, head_comment, contents, upload_date)
VALUES (47, 1, 0,'동일인물 테스트 댓글 1', now());

insert into comment
(board_id, member_id, head_comment, contents, upload_date)
VALUES (47, 1, 0,'동일인물 테스트 댓글 2', now());

insert into comment
(board_id, member_id, head_comment, contents, upload_date)
VALUES (47, 2, 0,'테스트 댓글 3', now());

insert into comment
(board_id, member_id, head_comment, contents, upload_date)
VALUES (47, 2, 1,'테스트 대댓글 1', now());

insert into comment
(board_id, member_id, head_comment, contents, upload_date)
VALUES (47, 1, 1,'본인 테스트 대댓글 1', now());