drop table if exists manager CASCADE;
create table manager
(
    manager_id                  bigint generated by default as identity,
    manager_login_id            varchar(30) unique,
    manager_password            varchar(40),
    second_manager_password       varchar(40),
    manager_name                varchar(20),
    primary key (manager_id)
);
insert into manager
(manager_login_id, manager_password, second_manager_password, manager_name)
VALUES ('admin', '0000', '1111', 'manager001');