drop table if exists member CASCADE;

create table member
(
    member_id       bigint generated by default as identity,
    login_id        varchar(30),
    member_password varchar(40),
    nick_name        varchar(30),
    member_name     varchar(20),
    email           varchar(40),
    join_date       date,
    black_list      varchar(2),
    member_point    int,
    primary key (member_id)
);

insert into member
(login_id, member_password, nick_name, member_name, email, join_date, black_list, member_point)
VALUES ('test001', 'test001', 'test001', 'test001', 'test001@naver.com', now(), 'N', 100)


insert into member
(login_id, member_password, nick_name, member_name, email, join_date, black_list, member_point)
VALUES ('test002', 'test002', 'test002', 'test002', 'test002@naver.com', now(), 'N', 100)
