drop table if exists quiz CASCADE;

create table quiz
(
    quiz_id                        bigint generated by default as identity,
    quiz_category                  varchar(20),
    quiz_title                     varchar(80),
    quiz_detail                    varchar(100),
    quiz_solve                     varchar(200),
    quiz_answer                    Boolean,
    quiz_occurred_problem_count    int,
    quiz_number_of_hits            int,
    quiz_date                      date,
    primary key (quiz_id)
);

INSERT INTO quiz (quiz_category, quiz_title, quiz_detail, quiz_solve, quiz_answer, quiz_occurred_problem_count, quiz_number_of_hits, quiz_date) values ('캔', '캔 분리수거에 대한 OX 퀴즈', '알루미늄캔은 재활용이 가능한 것일까요?', '알루미늄캔은 재활용이 가능합니다. 알루미늄은 자원의 낭비를 줄이고 환경 보호를 위해 재활용이 권장되는 재료 중 하나입니다. 따라서 알루미늄캔은 재활용이 가능하며, 분리수거 시 알루미늄캔만 따로 모아 처리해야 합니다.', TRUE, 0, 0, now());
INSERT INTO quiz (quiz_category, quiz_title, quiz_detail, quiz_solve, quiz_answer, quiz_occurred_problem_count, quiz_number_of_hits, quiz_date) values ('플라스틱', '플라스틱 분리수거에 대한 OX 퀴즈', '플라스틱 물병은 분리수거가 가능한 것일까요?', '플라스틱 물병은 재활용이 가능한 분리수거 대상입니다. 다만, 재활용을 위해서는 플라스틱 뚜껑과 라벨을 따로 분리해서 처리해야 하며, 물병 내부에 내용물이 남아 있으면 세척해주어야 합니다.', TRUE, 0, 0, now());
INSERT INTO quiz (quiz_category, quiz_title, quiz_detail, quiz_solve, quiz_answer, quiz_occurred_problem_count, quiz_number_of_hits, quiz_date) values ('유리병', '유리병 분리수거에 대한 OX 퀴즈', '유리병은 재활용이 불가능한 것일까요?', '유리병은 재활용이 가능한 분리수거 대상입니다. 하지만, 유리병을 분리수거할 때는 라벨과 뚜껑 등의 부속물을 제거해야 합니다. 라벨이나 뚜껑 등은 유리재료와 다른 재료로 이루어져 있어, 분리수거 시 함께 처리하면 재활용이 어려울 수 있습니다.', FALSE, 0, 0, now());
INSERT INTO quiz (quiz_category, quiz_title, quiz_detail, quiz_solve, quiz_answer, quiz_occurred_problem_count, quiz_number_of_hits, quiz_date) values ('종이', '종이컵 분리수거에 대한 OX 퀴즈', '종이컵은 재활용이 가능한 것일까요?', '종이컵은 대체로 재활용이 어렵습니다. 종이컵은 내부에 플라스틱 코팅이 되어 있거나, 다양한 재료로 인쇄되어 있는 경우가 많아서, 재활용을 위해서는 분리수거가 어렵습니다. 따라서 종이컵은 일반쓰레기로 처리해야 합니다.', FALSE, 0, 0, now());
INSERT INTO quiz (quiz_category, quiz_title, quiz_detail, quiz_solve, quiz_answer, quiz_occurred_problem_count, quiz_number_of_hits, quiz_date) values ('스티로폼', '스티로폼 분리수거에 대한 OX 퀴즈', '스티로폼은 재활용이 가능한 것일까요?', '스티로폼은 열에 강하고 가벼운 소재이지만, 그만큼 분해가 어려워 환경오염의 위험이 높습니다. 그래서 스티커나 테이프, 이물질을 모두 제거하고 오염된 부분은 세척하여 분리배출을 하고, 만약 오염 세척이 어렵다면 일반쓰레기로 버려야 합니다.', TRUE, 0, 0, now());
INSERT INTO quiz (quiz_category, quiz_title, quiz_detail, quiz_solve, quiz_answer, quiz_occurred_problem_count, quiz_number_of_hits, quiz_date) values ('캔', '캔 분리수거에 대한 OX 퀴즈', '스프레이캔은 재활용이 가능한 것일까요?', '스프레이캔은 재활용이 가능한 캔 중 하나입니다. 스프레이캔은 대개 압축가스가 들어있는데, 이를 안전하게 제거한 후 캔 자체를 분리수거하면 재활용이 가능합니다.', TRUE, 0, 0, now());
INSERT INTO quiz (quiz_category, quiz_title, quiz_detail, quiz_solve, quiz_answer, quiz_occurred_problem_count, quiz_number_of_hits, quiz_date) values ('유리병', '유리병 분리수거에 대한 OX 퀴즈', '유리병의 색상에 따라 분리수거가 필요한 것일까요?', '유리병의 색상에 따라 분리수거가 필요합니다. 유리병은 대개 초록색, 갈색, 투명색으로 나뉘며, 이는 제조 과정에서 사용되는 원료와 색소의 차이로 인해 발생합니다. 각각의 색상별로 분리하여 처리해야 하기 때문에, 유리병은 반드시 색상별로 분리하여 수거해야 합니다.', TRUE, 0, 0, now());
INSERT INTO quiz (quiz_category, quiz_title, quiz_detail, quiz_solve, quiz_answer, quiz_occurred_problem_count, quiz_number_of_hits, quiz_date) values ('플라스틱', '플라스틱 분리수거에 대한 OX 퀴즈', '투명한 플라스틱병만 재활용이 가능한 것일까요?', '플라스틱병은 종류에 따라 재활용이 가능하거나 불가능한 경우가 있습니다. 일반적으로 PET 플라스틱병은 재활용이 가능하지만, PVC, PP, PS 등의 플라스틱병은 재활용이 어렵거나 불가능합니다.', FALSE, 0, 0, now());
INSERT INTO quiz (quiz_category, quiz_title, quiz_detail, quiz_solve, quiz_answer, quiz_occurred_problem_count, quiz_number_of_hits, quiz_date) values ('일반 쓰레기', '일반 쓰레기 배출에 대한 OX 퀴즈', '화분은 재활용이 가능한 것일까요?', '화분은 일반 쓰레기입니다. 부피가 클 경우 대형 폐기물 신고 후 배출 수수료를 납부하고 배출해야 합니다.', FALSE, 0, 0, now());
INSERT INTO quiz (quiz_category, quiz_title, quiz_detail, quiz_solve, quiz_answer, quiz_occurred_problem_count, quiz_number_of_hits, quiz_date) values ('음식물 쓰레기', '음식물 쓰레기에 대한 OX 퀴즈', '고추장, 간장, 쌈장 등 장류는 음식물 쓰레기일까요?', '염분이 많은 장류는 음식물 쓰레기에 포함되지 않습니다.', FALSE, 0, 0, now());
INSERT INTO quiz (quiz_category, quiz_title, quiz_detail, quiz_solve, quiz_answer, quiz_occurred_problem_count, quiz_number_of_hits, quiz_date) values ('일반 쓰레기', '일반 쓰레기 배출에 대한 OX 퀴즈', '칫솔은 재활용 쓰레기일까요?', '칫솔은 플라스틱과 그 외의 재료로 구성되어 있기 때문에 플라스틱류가 아닌 일반 쓰레기로 분류해야 합니다.', FALSE, 0, 0, now());
INSERT INTO quiz (quiz_category, quiz_title, quiz_detail, quiz_solve, quiz_answer, quiz_occurred_problem_count, quiz_number_of_hits, quiz_date) values ('일반 쓰레기', '일반 쓰레기 배출에 대한 OX 퀴즈', '도자기, 사기는 재활용 쓰레기일까요?', '유리그릇은 재활용이 되지만 도자기와 사기는 일반 쓰레기입니다.', FALSE, 0, 0, now());
INSERT INTO quiz (quiz_category, quiz_title, quiz_detail, quiz_solve, quiz_answer, quiz_occurred_problem_count, quiz_number_of_hits, quiz_date) values ('일반 쓰레기', '일반 쓰레기 배출에 대한 OX 퀴즈', '일회용 플라스틱 빨대는 플라스틱류로 분리배출이 가능할까요?', '일회용 플라스틱 빨대는 일반 쓰레기로 분리배출해야 합니다.', FALSE, 0, 0, now());
INSERT INTO quiz (quiz_category, quiz_title, quiz_detail, quiz_solve, quiz_answer, quiz_occurred_problem_count, quiz_number_of_hits, quiz_date) values ('비닐', '비닐 분리수거에 대한 OX 퀴즈', '뽁뽁이는 일반 쓰레기로 배출해야 할까요?', '뽁뽁이는 비닐이기 때문에 분리배출을 한다면 재활용이 가능합니다.', FALSE, 0, 0, now());
INSERT INTO quiz (quiz_category, quiz_title, quiz_detail, quiz_solve, quiz_answer, quiz_occurred_problem_count, quiz_number_of_hits, quiz_date) values ('일반 쓰레기', '일반 쓰레기 배출에 대한 OX 퀴즈', '아이스팩은 일반 쓰레기로 배출해야 할까요?', '환경부에서는 일반 쓰레기 배출을 권장합니다. 그러나 내용물은 일반 쓰레기로 버리고 비닐은 비닐류로 분리배출이 가능합니다. ', TRUE, 0, 0, now());
INSERT INTO quiz (quiz_category, quiz_title, quiz_detail, quiz_solve, quiz_answer, quiz_occurred_problem_count, quiz_number_of_hits, quiz_date) values ('스티로폼', '스티로폼 분리수거에 대한 OX 퀴즈', '과일 포장재는 일반 쓰레기로 배출해야 할까요?', '과일 포장재로 쓰이는 종류는 재활용으로 가능한 플라스틱과 다른 재질이여서 일반 쓰레기로 배출해야 합니다.', TRUE, 0, 0, now());
INSERT INTO quiz (quiz_category, quiz_title, quiz_detail, quiz_solve, quiz_answer, quiz_occurred_problem_count, quiz_number_of_hits, quiz_date) values ('음식물 쓰레기', '음식물 쓰레기에 대한 OX 퀴즈', '밤과 호두, 은행, 조개 등의 어패류 껍데기, 과일의 씨는 음식물 쓰레기일까요?', '단단한 과일껍질이나 씨앗은 일반 쓰레기입니다. 어패류 껍데기는 석회질이 포함되어 있기 때문에 일반 쓰레기로 배출해야 합니다.', FALSE, 0, 0, now());
INSERT INTO quiz (quiz_category, quiz_title, quiz_detail, quiz_solve, quiz_answer, quiz_occurred_problem_count, quiz_number_of_hits, quiz_date) values ('종이', '종이류 분리수거에 대한 OX퀴즈', '기름이 묻은 종이상자도 재활용할 수 있을까요?', '재활용이 가능하지만 기름기와 양념 등을 최대한 닦아낸 뒤 분리배출해야 합니다. 박스 대부분이 오연된 상태일 경우 일반 쓰레기로 배출하고 더러워진 부분만 따로 찢어버리는 것도 좋은 방법입니다.', TRUE, 0, 0, now());
INSERT INTO quiz (quiz_category, quiz_title, quiz_detail, quiz_solve, quiz_answer, quiz_occurred_problem_count, quiz_number_of_hits, quiz_date) values ('종이', '종이류 분리수거에 대한 OX퀴즈', '코팅이 된 종이도 재활용이 가능할까요?', '손으로 찢기는 정도의 코팅은 종이류로 재활용이 가능합니다. 하지만 양면이 코팅되어 있고 손으로 찢었을 때 잘 찢기지 않는다면 일반 쓰레기로 배출해야 합니다.', TRUE, 0, 0, now());
INSERT INTO quiz (quiz_category, quiz_title, quiz_detail, quiz_solve, quiz_answer, quiz_occurred_problem_count, quiz_number_of_hits, quiz_date) values ('비닐', '비닐 분리수거에 대한 OX 퀴즈', '손바닥보다 작은 비닐 쓰레기는 재활용이 가능할까요?', '내용물을 깨끗하게 씻어내기 어려워 일반 쓰레기로 권장될 뿐 재활용이 가능합니다. 내용물이 묻어있다면 일반 쓰레기로, 깨끗이 세척했다면 비닐류로 버리면 됩니다.', TRUE, 0, 0, now());

