drop table if exists challenge CASCADE;
CREATE TABLE challenge (
                       challenge_id      bigint generated by default as identity,
                       title             varchar(100),
                       board_category    bigint,
                       contents          text,
                       start_challenge   timestamp,
                       end_challenge     timestamp,
                       join_member       int,
                       primary key (challenge_id)
);

insert into challenge
(title, board_category, contents, start_challenge, end_challenge, join_member)
values
('제목1', 3, '테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터', now(), now() + 60, 0);

insert into challenge
(title, board_category, contents, start_challenge, end_challenge, join_member)
values
('제목2', 3, '테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터', now(), now() + 60, 0);

insert into challenge
(title, board_category, contents, start_challenge, end_challenge, join_member)
values
('제목3', 3, '테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터', now(), now() + 60, 0);

insert into challenge
(title, board_category, contents, start_challenge, end_challenge, join_member)
values
('제목4', 3, '테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터', now(), now() + 60, 0);

insert into challenge
(title, board_category, contents, start_challenge, end_challenge, join_member)
values
('제목5', 3, '테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터', now(), now() + 60, 0);

insert into challenge
(title, board_category, contents, start_challenge, end_challenge, join_member)
values
('제목6', 3, '테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터', now(), now() + 60, 0);

insert into challenge
(title, board_category, contents, start_challenge, end_challenge, join_member)
values
('제목1', 3, '테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터', '2023-01-01', '2023-01-31', 0);

insert into challenge
(title, board_category, contents, start_challenge, end_challenge, join_member)
values
('제목2', 3, '테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터', '2023-02-01', '2023-02-28', 0);

insert into challenge
(title, board_category, contents, start_challenge, end_challenge, join_member)
values
('제목3', 3, '테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터', '2023-03-01', '2023-03-31', 0);

insert into challenge
(title, board_category, contents, start_challenge, end_challenge, join_member)
values
('제목4', 3, '테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터 테스트 데이터', '2023-04-01', '2023-04-30', 0);