drop table if exists member CASCADE;

create table member
(
    member_id       bigint generated by default as identity,
    login_id        varchar(30) unique,
    member_password varchar(40),
    nick_name       varchar(30) unique,
    member_name     varchar(20),
    email           varchar(40) unique,
    join_date       date,
    black_list      varchar(2),
    member_point    int,
    primary key (member_id)
);


drop table if exists quiz CASCADE;

create table quiz
(
    quiz_id                        bigint generated by default as identity,
    quiz_category                  varchar(20),
    quiz_title                     varchar(80),
    quiz_detail                    varchar(100),
    quiz_solve                     varchar(200),
    quiz_answer                    Boolean,
    quiz_occurred_problem_count    int,
    quiz_number_of_hits            int,
    quiz_date                      date,
    primary key (quiz_id)
);

drop table if exists board CASCADE;
create table board
(
    board_id                  bigint generated by default as identity,
    title                     varchar(100),
    board_category            bigint,
    contents                  text,
    member_id                 bigint,
    upload_date               date,
    edit_date                 date,
    delete_date               date,
    views                     int,
    primary key (board_id)
);

drop table if exists thumbup CASCADE;

create table thumbup
(
    board_id         bigint,
    member_id        bigint,
    dateTime         timestamp,
    isDeleted        Boolean,

    primary key (board_id, member_id),
    FOREIGN KEY (board_id) REFERENCES board(board_id) on update cascade,
    FOREIGN KEY (member_id) REFERENCES member(member_id) on update cascade
);