drop table if exists member CASCADE;

create table member
(
    member_id       bigint generated by default as identity,
    login_id        varchar(30) unique,
    member_password varchar(40),
    nick_name       varchar(30) unique,
    member_name     varchar(20),
    email           varchar(40) unique,
    join_date       date,
    black_list      varchar(2),
    member_point    int,
    primary key (member_id)
);


drop table if exists quiz CASCADE;

create table quiz
(
    quiz_id                        bigint generated by default as identity,
    quiz_category                  varchar(20),
    quiz_title                     varchar(80),
    quiz_detail                    varchar(100),
    quiz_solve                     varchar(200),
    quiz_answer                    Boolean,
    quiz_occurred_problem_count    int,
    quiz_number_of_hits            int,
    quiz_date                      date,
    primary key (quiz_id)
);